spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Aixac_Mornitering_Practice
    username: root
    password: 3306
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
#  org.hibernate.type: trace